on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/node-versions
        with:
          node-version: 20

      - name: Run Lint and Test
        # Install a project with a clean slate (required package-lock.json)
        # npm ci will: Delete the node_modules folder
        # npm ci will: Install all package-lock.json dependencies.
        run: |
          npm ci
          npm run lint
          npm test
